server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service #lb from load balancer. The load balancer chooses the best instance of a microservice (the one with the least traffic).
          predicates:
            - Path=/api/users/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/api/cars/**
        - id: motorbike-service
          uri: lb://motorbike-service
          predicates:
            - Path=/api/motorbikes/**